### ISSUE TITLE
Missing dependency ada-next/lib/utils/AdaStoreProvider in ./pages/_app.js 

### ISSUE THREAD

**Issue by ranzen** [StudioNAND/next-template#1]
- Cloned the repo
- npm install
- npm start 

throws:
```
This dependency was not found:
* ada-next/lib/utils/AdaStoreProvider in ./pages/_app.js 
To install it, you can run: npm install --save ada-next/lib/utils/AdaStoreProvider
```

Running npm install --save ada-next/lib/utils/AdaStoreProvider throws 
`Could not install from "ada-next/lib/utils/AdaStoreProvider" as it does not contain a package.json` file.

**Comment by maerzhase** [comment]
glad to see the template being used! :-) you can just remove the import and the use of the component. this is an artifact i forgot to remove. will do that for the template aswell...
